CREATE DATABASE TarefasDb;

USE TarefasDb;

CREATE TABLE Tarefa(
	IdTarefa UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	Titulo NVARCHAR(255) NOT NULL,
	Descricao TEXT NOT NULL,
	"Status" BIT NOT NULL,
	"Data" DATETIME2 DEFAULT GETDATE()
);

SELECT * FROM Tarefa;